FORMAT: 1A
HOST: https://ehif.gitsvg.se/

# EHiF

> **OBS! Denna dokumentation håller på att skrivas och är endast för internt bruk.**

API för EHiF &mdash; Elevens Hälsa i Fokus.

Alla anrop kräver autentisering med SITHS-certifikat.

## Triggerprotokoll [/api/trigger]

### Informera om sparad elevhälsoenkät [POST]

Skickas från ett externt system för att informera om att en elevhälsoenkät sparats och finns att hämta via tjänsteplattformen. 

+ Request (application/json)
    + Attributes(SubmitTrigger)

+ Response 200 (application/json)
    + Attributes
        + message: `null` (string)
        + code: `0` (number)

# Data Structures

## SubmitTrigger (object)
+ subjectKey: `19620831-5116` (string, required) - Personnummer
+ submittedAt: `2019-01-29 12:49:00` (string, required) - Tidsstämpel när triggern skickades [ISO8601]
+ systemID: `SE12345678901234-5678` (string, required) - Anropande systems HSAID
+ goVersion: `1.1` (string) - Kontraktsversion att använda mot NTjP och getObservations
+ formID: `ehif-4-1.0` (string, required) - Formulärets ID [typ och version]
+ careProviderID: `SE98765432109890-1234` (string, required) - Vårdgivarens HSAID
+ schoolUnitID: `74174879` (number, required) - Skolenhetens ID enligt SCB:s Skolenhetsregister
+ schoolClass: `4a` (string, required) - Klassens ID enligt skolan