FORMAT: 1A
HOST: https://ehif.gitsvg.se/

# EHiF

> **OBS! Denna dokumentation håller på att skrivas och är endast för internt bruk.**

API för EHiF &mdash; Elevens Hälsa i Fokus.

Alla anrop kräver tvåfaktorautentisering om inte api-nyckel finns med i exempelanropet.

## Triggerprotokoll [/api/trigger]

### Informera om sparad elevhälsoenkät [POST]

Skickas från ett externt system för att informera om att en elevhälsoenkät sparats i systemet. 

+ Request (application/json)
    + Attributes(SubmitTrigger)

+ Response 200 (application/json)
    + Attributes
        + message: `null` (string)
        + code: `0` (number)

## Autentisering [/api/authenticate]

### Hämta autentiserad session [GET]

+ Response 200 (application/json)

        {
            "code": 0
        }
        
        
# Data Structures

## SubmitTrigger (object)
+ subjectKey: `19620831-5116` (string, required) - Personnummer
+ sentAt: `2019-01-29 12:49:00` (string, required) - Tidsstämpel när triggern skickades ISO8601
+ systemID: `SE12345678901234-5678` (string, required) - Anropande systems HSAID
+ careUnitID: `SE98765432109890-6543` (string, required) - Vårdenhetens HSAID 
+ careGiverID: `SE98765432109890-1234` (string, required) - Vårdgivarens HSAID
+ schoolUnitID: `74174879` (number, required) - Skolenhetens ID enligt SCB:s Skolenhetsregister 
+ getObservationsVersion: `1.1` (string, required) - Kontraktsversion att använda mot NTjP och getObservations
+ formID: `ehif-4-1.0` (string, required) - Formulärtyp och version